/**
 * BASE SEMENTE — ~190 locais reais do Brasil, digitados à mão.
 *
 * Serve para a aplicação funcionar imediatamente, sem internet para os dados.
 * A base GRANDE (milhares de locais com fotos) é gerada pelo script
 *   python3 scripts/gerar_base_wikidata.py
 * que cria o arquivo dados/locais.js a partir do Wikidata/Wikimedia Commons.
 *
 * Coordenadas aproximadas. Relevância ∈ [0, 1] estimada manualmente
 * (na base do Wikidata ela é calculada pelo número de artigos na Wikipédia).
 *
 * Formato compacto: [nome, categoria, cidade, UF, lat, lon, relevância, descrição]
 */
(function (raiz) {
  const L = [
    // ------------------------------------------------------------ cidades
    ['São Paulo', 'cidade', 'São Paulo', 'SP', -23.5505, -46.6333, 1.0, 'Maior cidade do Brasil e principal centro financeiro da América do Sul.'],
    ['Rio de Janeiro', 'cidade', 'Rio de Janeiro', 'RJ', -22.9068, -43.1729, 1.0, 'Antiga capital federal, conhecida pela paisagem entre o mar e as montanhas.'],
    ['Brasília', 'cidade', 'Brasília', 'DF', -15.7939, -47.8828, 0.95, 'Capital federal planejada por Lúcio Costa e Oscar Niemeyer, inaugurada em 1960.'],
    ['Salvador', 'cidade', 'Salvador', 'BA', -12.9777, -38.5016, 0.9, 'Primeira capital do Brasil, centro da cultura afro-brasileira.'],
    ['Fortaleza', 'cidade', 'Fortaleza', 'CE', -3.7319, -38.5267, 0.85, 'Capital cearense de orla extensa e intensa vida noturna.'],
    ['Belo Horizonte', 'cidade', 'Belo Horizonte', 'MG', -19.9167, -43.9345, 0.85, 'Capital mineira planejada no fim do século XIX, cercada pela Serra do Curral.'],
    ['Manaus', 'cidade', 'Manaus', 'AM', -3.1190, -60.0217, 0.85, 'Maior cidade da Amazônia, às margens do Rio Negro.'],
    ['Curitiba', 'cidade', 'Curitiba', 'PR', -25.4284, -49.2733, 0.8, 'Capital paranaense conhecida pelo planejamento urbano e pelos parques.'],
    ['Recife', 'cidade', 'Recife', 'PE', -8.0476, -34.8770, 0.85, 'Capital pernambucana cortada por rios e pontes, berço do frevo.'],
    ['Porto Alegre', 'cidade', 'Porto Alegre', 'RS', -30.0346, -51.2177, 0.8, 'Capital gaúcha às margens do Lago Guaíba.'],
    ['Belém', 'cidade', 'Belém', 'PA', -1.4558, -48.4902, 0.8, 'Porta de entrada da Amazônia, famosa pelo Círio de Nazaré.'],
    ['Goiânia', 'cidade', 'Goiânia', 'GO', -16.6869, -49.2648, 0.7, 'Capital goiana de traçado art déco, planejada nos anos 1930.'],
    ['São Luís', 'cidade', 'São Luís', 'MA', -2.5307, -44.3068, 0.7, 'Capital maranhense com centro histórico de azulejos portugueses.'],
    ['Maceió', 'cidade', 'Maceió', 'AL', -9.6658, -35.7353, 0.7, 'Capital alagoana de águas verdes e piscinas naturais.'],
    ['Natal', 'cidade', 'Natal', 'RN', -5.7945, -35.2110, 0.7, 'Capital potiguar das dunas e do Forte dos Reis Magos.'],
    ['Teresina', 'cidade', 'Teresina', 'PI', -5.0920, -42.8038, 0.65, 'Capital piauiense entre os rios Parnaíba e Poti.'],
    ['João Pessoa', 'cidade', 'João Pessoa', 'PB', -7.1195, -34.8450, 0.7, 'Capital paraibana, uma das cidades mais antigas e arborizadas do país.'],
    ['Aracaju', 'cidade', 'Aracaju', 'SE', -10.9472, -37.0731, 0.65, 'Capital sergipana planejada, com orla de Atalaia.'],
    ['Cuiabá', 'cidade', 'Cuiabá', 'MT', -15.6014, -56.0979, 0.65, 'Capital mato-grossense, ponto de partida para o Pantanal.'],
    ['Campo Grande', 'cidade', 'Campo Grande', 'MS', -20.4697, -54.6201, 0.65, 'Capital sul-mato-grossense, conhecida como Cidade Morena.'],
    ['Florianópolis', 'cidade', 'Florianópolis', 'SC', -27.5954, -48.5480, 0.75, 'Capital catarinense, em grande parte situada na Ilha de Santa Catarina.'],
    ['Vitória', 'cidade', 'Vitória', 'ES', -20.3155, -40.3128, 0.65, 'Capital capixaba, construída sobre uma ilha.'],
    ['Porto Velho', 'cidade', 'Porto Velho', 'RO', -8.7612, -63.9004, 0.55, 'Capital de Rondônia, às margens do Rio Madeira.'],
    ['Rio Branco', 'cidade', 'Rio Branco', 'AC', -9.9754, -67.8249, 0.55, 'Capital acreana, no coração da Amazônia ocidental.'],
    ['Macapá', 'cidade', 'Macapá', 'AP', 0.0349, -51.0694, 0.55, 'Capital amapaense, cortada pela Linha do Equador.'],
    ['Boa Vista', 'cidade', 'Boa Vista', 'RR', 2.8235, -60.6758, 0.55, 'Única capital brasileira totalmente ao norte do Equador.'],
    ['Palmas', 'cidade', 'Palmas', 'TO', -10.2491, -48.3243, 0.55, 'Capital mais jovem do país, fundada em 1989.'],
    ['Ouro Preto', 'cidade', 'Ouro Preto', 'MG', -20.3856, -43.5035, 0.75, 'Cidade colonial do ciclo do ouro, Patrimônio Mundial da UNESCO.'],
    ['Paraty', 'cidade', 'Paraty', 'RJ', -23.2178, -44.7131, 0.7, 'Vila colonial à beira-mar, sede da Festa Literária Internacional.'],
    ['Olinda', 'cidade', 'Olinda', 'PE', -8.0089, -34.8553, 0.7, 'Centro histórico colonial no alto das colinas, famoso pelo carnaval de bonecos gigantes.'],
    ['Campina Grande', 'cidade', 'Campina Grande', 'PB', -7.2307, -35.8817, 0.55, 'Polo tecnológico do interior paraibano, sede de um dos maiores São João do país.'],
    ['Petrópolis', 'cidade', 'Petrópolis', 'RJ', -22.5112, -43.1779, 0.6, 'Cidade Imperial na serra fluminense.'],
    ['Foz do Iguaçu', 'cidade', 'Foz do Iguaçu', 'PR', -25.5163, -54.5854, 0.65, 'Cidade da tríplice fronteira, vizinha às Cataratas do Iguaçu.'],
    ['Gramado', 'cidade', 'Gramado', 'RS', -29.3787, -50.8747, 0.6, 'Cidade serrana de arquitetura alpina e festival de cinema.'],
    ['Tiradentes', 'cidade', 'Tiradentes', 'MG', -21.1102, -44.1781, 0.55, 'Pequena cidade colonial mineira, conhecida pela gastronomia.'],
    ['Lençóis', 'cidade', 'Lençóis', 'BA', -12.5636, -41.3903, 0.5, 'Antiga cidade do diamante, porta de entrada da Chapada Diamantina.'],
    ['Bonito', 'cidade', 'Bonito', 'MS', -21.1261, -56.4836, 0.55, 'Destino de ecoturismo com rios de águas cristalinas.'],
    ['Santos', 'cidade', 'Santos', 'SP', -23.9608, -46.3336, 0.6, 'Cidade do maior porto da América Latina e do maior jardim de praia do mundo.'],
    ['Blumenau', 'cidade', 'Blumenau', 'SC', -26.9194, -49.0661, 0.5, 'Cidade de colonização alemã, sede da Oktoberfest brasileira.'],
    ['Juazeiro do Norte', 'cidade', 'Juazeiro do Norte', 'CE', -7.2131, -39.3151, 0.45, 'Centro de romarias ligado à figura do Padre Cícero.'],
    ['Caruaru', 'cidade', 'Caruaru', 'PE', -8.2760, -35.9819, 0.45, 'Capital do forró e da arte figurativa do barro.'],
    ['Mariana', 'cidade', 'Mariana', 'MG', -20.3778, -43.4161, 0.5, 'Primeira capital de Minas Gerais, com casario barroco.'],
    ['Diamantina', 'cidade', 'Diamantina', 'MG', -18.2413, -43.6033, 0.5, 'Cidade colonial do ciclo do diamante, Patrimônio Mundial.'],
    ['São Cristóvão', 'cidade', 'São Cristóvão', 'SE', -11.0084, -37.2044, 0.4, 'Quarta cidade mais antiga do Brasil, com a Praça São Francisco tombada pela UNESCO.'],
    ['Cachoeira', 'cidade', 'Cachoeira', 'BA', -12.6183, -38.9558, 0.4, 'Cidade histórica do Recôncavo Baiano.'],

    // ------------------------------------------------------------ praias
    ['Praia de Copacabana', 'praia', 'Rio de Janeiro', 'RJ', -22.9711, -43.1822, 0.95, 'Praia símbolo do Rio, com calçadão de ondas desenhado por Burle Marx.'],
    ['Praia de Ipanema', 'praia', 'Rio de Janeiro', 'RJ', -22.9868, -43.2048, 0.9, 'Praia eternizada pela bossa nova, com o pôr do sol no Arpoador.'],
    ['Praia da Barra da Tijuca', 'praia', 'Rio de Janeiro', 'RJ', -23.0110, -43.3650, 0.55, 'A mais extensa praia da cidade do Rio, com cerca de 18 km.'],
    ['Praia de Grumari', 'praia', 'Rio de Janeiro', 'RJ', -23.0480, -43.5260, 0.35, 'Praia selvagem protegida por área de preservação ambiental.'],
    ['Praia do Forno', 'praia', 'Arraial do Cabo', 'RJ', -22.9700, -42.0160, 0.45, 'Enseada de água clara acessível por trilha ou barco.'],
    ['Praia de Geribá', 'praia', 'Armação dos Búzios', 'RJ', -22.7790, -41.9100, 0.45, 'Praia de ondas de Búzios, preferida dos surfistas.'],
    ['Praia do Forte', 'praia', 'Mata de São João', 'BA', -12.5786, -38.0003, 0.55, 'Vila de pescadores com base do Projeto Tamar.'],
    ['Morro de São Paulo', 'praia', 'Cairu', 'BA', -13.3800, -38.9130, 0.55, 'Vila sem carros na Ilha de Tinharé, com praias numeradas.'],
    ['Praia de Trancoso', 'praia', 'Porto Seguro', 'BA', -16.5900, -39.0930, 0.5, 'Vila do Quadrado e falésias sobre praias extensas.'],
    ['Praia do Espelho', 'praia', 'Porto Seguro', 'BA', -16.7480, -39.1170, 0.4, 'Piscinas naturais que refletem o céu na maré baixa.'],
    ['Praia de Itacaré', 'praia', 'Itacaré', 'BA', -14.2770, -38.9970, 0.5, 'Sequência de praias cercadas de Mata Atlântica, famosa pelo surfe.'],
    ['Porto de Galinhas', 'praia', 'Ipojuca', 'PE', -8.5070, -35.0003, 0.7, 'Piscinas naturais de recifes, um dos destinos mais visitados do Nordeste.'],
    ['Praia de Boa Viagem', 'praia', 'Recife', 'PE', -8.1180, -34.8910, 0.6, 'Praia urbana do Recife protegida por uma linha de arrecifes.'],
    ['Praia dos Carneiros', 'praia', 'Tamandaré', 'PE', -8.7040, -35.0840, 0.5, 'Coqueiral e a pequena Igreja de São Benedito à beira-mar.'],
    ['Baía do Sancho', 'praia', 'Fernando de Noronha', 'PE', -3.8540, -32.4430, 0.7, 'Frequentemente eleita a praia mais bonita do mundo, acessada por escadas na rocha.'],
    ['Praia de Iracema', 'praia', 'Fortaleza', 'CE', -3.7212, -38.5160, 0.5, 'Bairro boêmio e praia da Ponte dos Ingleses.'],
    ['Praia do Futuro', 'praia', 'Fortaleza', 'CE', -3.7488, -38.4585, 0.45, 'Faixa de areia com grandes barracas de praia.'],
    ['Jericoacoara', 'praia', 'Jijoca de Jericoacoara', 'CE', -2.7975, -40.5137, 0.75, 'Vila de areia entre dunas, lagoas e a Pedra Furada.'],
    ['Praia da Pipa', 'praia', 'Tibau do Sul', 'RN', -6.2290, -35.0450, 0.6, 'Falésias coloridas e golfinhos na Baía dos Golfinhos.'],
    ['Praia de Ponta Negra', 'praia', 'Natal', 'RN', -5.8794, -35.1714, 0.5, 'Praia urbana de Natal aos pés do Morro do Careca.'],
    ['Praia de Tambaú', 'praia', 'João Pessoa', 'PB', -7.1155, -34.8235, 0.5, 'Orla central de João Pessoa, ponto de saída para o Picãozinho.'],
    ['Praia do Cabo Branco', 'praia', 'João Pessoa', 'PB', -7.1427, -34.7996, 0.45, 'Praia de falésia junto ao ponto mais oriental das Américas.'],
    ['Praia de Coqueirinho', 'praia', 'Conde', 'PB', -7.3195, -34.8000, 0.35, 'Falésias avermelhadas e coqueirais no litoral sul paraibano.'],
    ['Praia de Tambaba', 'praia', 'Conde', 'PB', -7.3640, -34.7980, 0.4, 'Primeira praia oficial de naturismo do Nordeste.'],
    ['Praia de Pajuçara', 'praia', 'Maceió', 'AL', -9.6683, -35.7193, 0.45, 'Jangadas levam às piscinas naturais a 2 km da costa.'],
    ['Praia do Francês', 'praia', 'Marechal Deodoro', 'AL', -9.7680, -35.8390, 0.45, 'Mar calmo protegido por recifes e trecho de ondas para surfe.'],
    ['Maragogi', 'praia', 'Maragogi', 'AL', -9.0120, -35.2220, 0.55, 'Galés de Maragogi, piscinas naturais conhecidas como Caribe brasileiro.'],
    ['Praia de Atalaia', 'praia', 'Aracaju', 'SE', -10.9900, -37.0470, 0.4, 'Orla urbana de Aracaju com os Arcos da Orla.'],
    ['Praia da Joaquina', 'praia', 'Florianópolis', 'SC', -27.6292, -48.4489, 0.5, 'Dunas para sandboard e ondas de campeonatos de surfe.'],
    ['Praia Mole', 'praia', 'Florianópolis', 'SC', -27.6030, -48.4330, 0.35, 'Praia de areia grossa cercada por morros.'],
    ['Praia Central de Balneário Camboriú', 'praia', 'Balneário Camboriú', 'SC', -26.9900, -48.6340, 0.5, 'Orla de arranha-céus e roda-gigante.'],
    ['Praia do Rosa', 'praia', 'Imbituba', 'SC', -28.1290, -48.6440, 0.4, 'Baía onde baleias-francas aparecem no inverno.'],
    ['Praia do Cassino', 'praia', 'Rio Grande', 'RS', -32.1870, -52.1590, 0.45, 'Considerada a praia mais extensa do mundo, com mais de 200 km.'],
    ['Praia do Félix', 'praia', 'Ubatuba', 'SP', -23.3920, -45.0050, 0.3, 'Enseada cercada de Mata Atlântica no litoral norte paulista.'],
    ['Praia de Maresias', 'praia', 'São Sebastião', 'SP', -23.7930, -45.5610, 0.4, 'Praia de ondas fortes e vida noturna no litoral norte paulista.'],
    ['Alter do Chão', 'praia', 'Santarém', 'PA', -2.5030, -54.9530, 0.55, 'Praias de rio no Tapajós, com a Ilha do Amor.'],

    // ------------------------------------------------------------ museus
    ['Museu de Arte de São Paulo (MASP)', 'museu', 'São Paulo', 'SP', -23.5614, -46.6559, 0.85, 'Acervo de arte ocidental exposto em cavaletes de vidro sob o vão livre de Lina Bo Bardi.'],
    ['Museu Paulista (Museu do Ipiranga)', 'museu', 'São Paulo', 'SP', -23.5855, -46.6097, 0.7, 'Palácio no local da Independência, reaberto em 2022.'],
    ['Pinacoteca de São Paulo', 'museu', 'São Paulo', 'SP', -23.5342, -46.6339, 0.65, 'Mais antigo museu de arte da cidade, com acervo de arte brasileira.'],
    ['Museu da Língua Portuguesa', 'museu', 'São Paulo', 'SP', -23.5345, -46.6346, 0.6, 'Museu interativo dedicado ao idioma, na Estação da Luz.'],
    ['Museu do Futebol', 'museu', 'São Paulo', 'SP', -23.5475, -46.6650, 0.55, 'Instalado sob as arquibancadas do Estádio do Pacaembu.'],
    ['Museu Afro Brasil', 'museu', 'São Paulo', 'SP', -23.5850, -46.6560, 0.45, 'Acervo sobre a história e a arte afro-brasileira no Parque Ibirapuera.'],
    ['Museu do Amanhã', 'museu', 'Rio de Janeiro', 'RJ', -22.8944, -43.1795, 0.75, 'Museu de ciências projetado por Santiago Calatrava na Praça Mauá.'],
    ['Museu Nacional', 'museu', 'Rio de Janeiro', 'RJ', -22.9057, -43.2263, 0.8, 'Instituição científica mais antiga do país, no Paço de São Cristóvão.'],
    ['Museu Nacional de Belas Artes', 'museu', 'Rio de Janeiro', 'RJ', -22.9088, -43.1754, 0.55, 'Grande acervo de arte brasileira do século XIX na Cinelândia.'],
    ['Museu Histórico Nacional', 'museu', 'Rio de Janeiro', 'RJ', -22.9050, -43.1700, 0.55, 'Complexo arquitetônico junto à Praça XV, com a história do Brasil.'],
    ['Museu de Arte Contemporânea de Niterói', 'museu', 'Niterói', 'RJ', -22.9075, -43.1259, 0.65, 'Edifício em forma de disco de Niemeyer sobre o mirante da Boa Viagem.'],
    ['Museu Imperial', 'museu', 'Petrópolis', 'RJ', -22.5079, -43.1768, 0.6, 'Antigo palácio de verão de D. Pedro II.'],
    ['Instituto Inhotim', 'museu', 'Brumadinho', 'MG', -20.1250, -44.2190, 0.75, 'Museu de arte contemporânea ao ar livre e jardim botânico.'],
    ['Museu da Inconfidência', 'museu', 'Ouro Preto', 'MG', -20.3858, -43.5036, 0.55, 'Antiga Casa de Câmara e Cadeia dedicada à Inconfidência Mineira.'],
    ['Museu de Arte da Pampulha', 'museu', 'Belo Horizonte', 'MG', -19.8510, -43.9780, 0.45, 'Antigo cassino projetado por Niemeyer às margens da Lagoa da Pampulha.'],
    ['Museu Oscar Niemeyer', 'museu', 'Curitiba', 'PR', -25.4103, -49.2669, 0.6, 'Conhecido como Museu do Olho, dedicado a artes visuais e design.'],
    ['Museu Paraense Emílio Goeldi', 'museu', 'Belém', 'PA', -1.4511, -48.4772, 0.5, 'Instituição de pesquisa amazônica com parque zoobotânico.'],
    ['Museu do Homem do Nordeste', 'museu', 'Recife', 'PE', -8.0360, -34.9180, 0.45, 'Acervo antropológico idealizado por Gilberto Freyre.'],
    ['Instituto Ricardo Brennand', 'museu', 'Recife', 'PE', -8.0565, -34.9640, 0.55, 'Castelo com armaria e a maior coleção de pinturas de Frans Post.'],
    ['Paço do Frevo', 'museu', 'Recife', 'PE', -8.0632, -34.8716, 0.35, 'Espaço dedicado ao frevo, Patrimônio Imaterial da Humanidade.'],
    ['Museu Cais do Sertão', 'museu', 'Recife', 'PE', -8.0610, -34.8710, 0.4, 'Museu sobre o sertão e a obra de Luiz Gonzaga no porto do Recife.'],
    ['Centro Dragão do Mar de Arte e Cultura', 'museu', 'Fortaleza', 'CE', -3.7230, -38.5130, 0.5, 'Complexo cultural com museus, planetário e cinemas.'],
    ['Museu da Gente Sergipana', 'museu', 'Aracaju', 'SE', -10.9180, -37.0490, 0.35, 'Museu interativo sobre a cultura de Sergipe.'],
    ['Museu da Amazônia (MUSA)', 'museu', 'Manaus', 'AM', -3.0040, -59.9400, 0.4, 'Museu a céu aberto na Reserva Ducke, com torre de observação da floresta.'],

    // ------------------------------------------------------------ parques
    ['Parque Nacional do Iguaçu', 'parque', 'Foz do Iguaçu', 'PR', -25.6200, -54.4800, 0.9, 'Unidade de conservação de Mata Atlântica que protege as cataratas.'],
    ['Parque Ibirapuera', 'parque', 'São Paulo', 'SP', -23.5874, -46.6576, 0.75, 'Principal parque urbano paulistano, com edifícios de Niemeyer.'],
    ['Parque Nacional da Tijuca', 'parque', 'Rio de Janeiro', 'RJ', -22.9520, -43.2840, 0.7, 'Floresta urbana replantada no século XIX.'],
    ['Jardim Botânico do Rio de Janeiro', 'parque', 'Rio de Janeiro', 'RJ', -22.9673, -43.2245, 0.65, 'Fundado por D. João VI em 1808, famoso pela aleia de palmeiras-imperiais.'],
    ['Parque Nacional da Chapada Diamantina', 'parque', 'Lençóis', 'BA', -12.5900, -41.4000, 0.7, 'Serras, grutas e cachoeiras no centro da Bahia.'],
    ['Parque Nacional da Chapada dos Veadeiros', 'parque', 'Alto Paraíso de Goiás', 'GO', -14.1000, -47.6500, 0.65, 'Cerrado de altitude com cânions e cachoeiras.'],
    ['Parque Nacional dos Lençóis Maranhenses', 'parque', 'Barreirinhas', 'MA', -2.5300, -43.1200, 0.85, 'Dunas brancas com lagoas de água da chuva entre elas.'],
    ['Parque Nacional da Serra da Capivara', 'parque', 'São Raimundo Nonato', 'PI', -8.8300, -42.5500, 0.6, 'Maior concentração de sítios de arte rupestre das Américas.'],
    ['Parque Nacional de Jericoacoara', 'parque', 'Jijoca de Jericoacoara', 'CE', -2.8500, -40.4500, 0.5, 'Dunas, mangues e a Pedra Furada.'],
    ['Parque Nacional da Serra dos Órgãos', 'parque', 'Teresópolis', 'RJ', -22.4580, -43.0000, 0.5, 'Picos graníticos como o Dedo de Deus.'],
    ['Parque Nacional do Itatiaia', 'parque', 'Itatiaia', 'RJ', -22.4300, -44.6200, 0.5, 'Primeiro parque nacional do Brasil, criado em 1937.'],
    ['Parque Nacional do Pantanal Matogrossense', 'parque', 'Poconé', 'MT', -17.8000, -57.5500, 0.6, 'Área alagável de grande biodiversidade.'],
    ['Parque Nacional da Chapada dos Guimarães', 'parque', 'Chapada dos Guimarães', 'MT', -15.4000, -55.8300, 0.55, 'Paredões de arenito no centro geodésico da América do Sul.'],
    ['Parque Nacional Marinho de Fernando de Noronha', 'parque', 'Fernando de Noronha', 'PE', -3.8500, -32.4200, 0.8, 'Arquipélago protegido com golfinhos-rotadores e tartarugas.'],
    ['Parque Nacional de Aparados da Serra', 'parque', 'Cambará do Sul', 'RS', -29.1700, -50.1000, 0.55, 'Cânion do Itaimbezinho na borda do planalto.'],
    ['Parque Estadual do Jalapão', 'parque', 'Mateiros', 'TO', -10.5500, -46.6000, 0.55, 'Dunas alaranjadas, fervedouros e capim-dourado.'],
    ['Parque Nacional da Serra da Canastra', 'parque', 'São Roque de Minas', 'MG', -20.2500, -46.6000, 0.5, 'Nascente do Rio São Francisco.'],
    ['Parque Nacional de Ubajara', 'parque', 'Ubajara', 'CE', -3.8370, -40.9000, 0.4, 'Gruta calcária acessada por bondinho.'],
    ['Parque Nacional do Catimbau', 'parque', 'Buíque', 'PE', -8.5200, -37.2500, 0.35, 'Caatinga, formações de arenito e pinturas rupestres.'],
    ['Parque Nacional de Anavilhanas', 'parque', 'Novo Airão', 'AM', -2.3800, -60.9200, 0.5, 'Um dos maiores arquipélagos fluviais do mundo, no Rio Negro.'],
    ['Parque Estadual de Vila Velha', 'parque', 'Ponta Grossa', 'PR', -25.2400, -50.0100, 0.45, 'Arenitos esculpidos pelo vento e furnas.'],
    ['Parque Estadual Pedra da Boca', 'parque', 'Araruna', 'PB', -6.4600, -35.6800, 0.35, 'Formações rochosas para escalada e rapel no agreste paraibano.'],
    ['Jardim Botânico Benjamim Maranhão', 'parque', 'João Pessoa', 'PB', -7.1370, -34.8620, 0.3, 'Remanescente de Mata Atlântica conhecido como Mata do Buraquinho.'],
    ['Jardim Botânico de Curitiba', 'parque', 'Curitiba', 'PR', -25.4430, -49.2390, 0.65, 'Estufa de vidro e ferro inspirada no Palácio de Cristal.'],
    ['Parque Barigui', 'parque', 'Curitiba', 'PR', -25.4220, -49.3080, 0.35, 'Grande parque urbano com lago e capivaras.'],
    ['Parque da Cidade Sarah Kubitschek', 'parque', 'Brasília', 'DF', -15.8000, -47.9080, 0.4, 'Um dos maiores parques urbanos do mundo, com paisagismo de Burle Marx.'],
    ['Parque Farroupilha (Redenção)', 'parque', 'Porto Alegre', 'RS', -30.0370, -51.2140, 0.45, 'Parque mais tradicional de Porto Alegre, com o Brique da Redenção.'],

    // ------------------------------------------------------------ monumentos
    ['Cristo Redentor', 'monumento', 'Rio de Janeiro', 'RJ', -22.9519, -43.2105, 1.0, 'Estátua art déco no Corcovado, uma das Sete Maravilhas do Mundo Moderno.'],
    ['Pão de Açúcar', 'monumento', 'Rio de Janeiro', 'RJ', -22.9492, -43.1545, 0.9, 'Monumento natural acessado pelo bondinho desde 1912.'],
    ['Escadaria Selarón', 'monumento', 'Rio de Janeiro', 'RJ', -22.9154, -43.1791, 0.6, 'Escadaria coberta de azulejos pelo artista chileno Jorge Selarón.'],
    ['Arcos da Lapa', 'monumento', 'Rio de Janeiro', 'RJ', -22.9130, -43.1800, 0.6, 'Antigo aqueduto colonial por onde hoje passa o bondinho de Santa Teresa.'],
    ['Sambódromo da Marquês de Sapucaí', 'monumento', 'Rio de Janeiro', 'RJ', -22.9110, -43.1970, 0.55, 'Passarela do samba projetada por Niemeyer.'],
    ['Congresso Nacional', 'monumento', 'Brasília', 'DF', -15.7998, -47.8645, 0.8, 'Sede do Legislativo, com as cúpulas da Câmara e do Senado.'],
    ['Praça dos Três Poderes', 'monumento', 'Brasília', 'DF', -15.8015, -47.8610, 0.6, 'Praça que reúne Executivo, Legislativo e Judiciário.'],
    ['Palácio da Alvorada', 'monumento', 'Brasília', 'DF', -15.7930, -47.8250, 0.55, 'Residência oficial da Presidência, à beira do Lago Paranoá.'],
    ['Ponte JK', 'monumento', 'Brasília', 'DF', -15.8240, -47.8290, 0.5, 'Ponte de três arcos assimétricos sobre o Lago Paranoá.'],
    ['Elevador Lacerda', 'monumento', 'Salvador', 'BA', -12.9744, -38.5130, 0.65, 'Elevador urbano que liga a Cidade Baixa à Cidade Alta desde 1873.'],
    ['Pelourinho', 'monumento', 'Salvador', 'BA', -12.9714, -38.5080, 0.75, 'Centro histórico colonial colorido, Patrimônio Mundial.'],
    ['Monumento às Bandeiras', 'monumento', 'São Paulo', 'SP', -23.5810, -46.6560, 0.5, 'Escultura de Victor Brecheret na entrada do Ibirapuera.'],
    ['Mercado Municipal de São Paulo', 'monumento', 'São Paulo', 'SP', -23.5417, -46.6292, 0.55, 'Mercadão com vitrais e o famoso sanduíche de mortadela.'],
    ['Ponte Octávio Frias de Oliveira', 'monumento', 'São Paulo', 'SP', -23.6000, -46.6930, 0.4, 'Ponte estaiada sobre o Rio Pinheiros.'],
    ['Memorial da América Latina', 'monumento', 'São Paulo', 'SP', -23.5275, -46.6650, 0.45, 'Conjunto de Niemeyer dedicado à integração latino-americana.'],
    ['Mercado Ver-o-Peso', 'monumento', 'Belém', 'PA', -1.4530, -48.5040, 0.65, 'Maior feira ao ar livre da América Latina, à beira da Baía do Guajará.'],
    ['Marco Zero do Recife', 'monumento', 'Recife', 'PE', -8.0631, -34.8711, 0.5, 'Praça Rio Branco com vista para o Parque das Esculturas de Brennand.'],
    ['Ponta do Seixas', 'monumento', 'João Pessoa', 'PB', -7.1550, -34.7930, 0.5, 'Ponto mais oriental do continente americano.'],
    ['Farol do Cabo Branco', 'monumento', 'João Pessoa', 'PB', -7.1480, -34.7960, 0.4, 'Farol triangular inspirado na folha do sisal.'],
    ['Estação Cabo Branco', 'monumento', 'João Pessoa', 'PB', -7.1460, -34.7970, 0.35, 'Centro de ciência, cultura e artes projetado por Niemeyer.'],
    ['Ponte Hercílio Luz', 'monumento', 'Florianópolis', 'SC', -27.5940, -48.5660, 0.6, 'Ponte pênsil de 1926 que liga a ilha ao continente.'],
    ['Estátua do Padre Cícero', 'monumento', 'Juazeiro do Norte', 'CE', -7.1910, -39.3260, 0.45, 'Estátua de 27 metros na Colina do Horto.'],
    ['Usina do Gasômetro', 'monumento', 'Porto Alegre', 'RS', -30.0340, -51.2410, 0.4, 'Antiga usina convertida em centro cultural às margens do Guaíba.'],

    // ------------------------------------------------------------ igrejas
    ['Catedral Metropolitana de Brasília', 'igreja', 'Brasília', 'DF', -15.7984, -47.8754, 0.75, 'Estrutura hiperboloide de 16 colunas projetada por Niemeyer.'],
    ['Santuário Nacional de Aparecida', 'igreja', 'Aparecida', 'SP', -22.8519, -45.2340, 0.8, 'Maior santuário mariano do mundo.'],
    ['Catedral da Sé de São Paulo', 'igreja', 'São Paulo', 'SP', -23.5507, -46.6340, 0.65, 'Catedral neogótica no marco zero da cidade.'],
    ['Mosteiro de São Bento do Rio de Janeiro', 'igreja', 'Rio de Janeiro', 'RJ', -22.8970, -43.1780, 0.5, 'Interior barroco revestido de talha dourada.'],
    ['Catedral Metropolitana do Rio de Janeiro', 'igreja', 'Rio de Janeiro', 'RJ', -22.9108, -43.1806, 0.5, 'Catedral cônica moderna com vitrais de 64 metros.'],
    ['Igreja de São Francisco de Assis (Ouro Preto)', 'igreja', 'Ouro Preto', 'MG', -20.3860, -43.5025, 0.6, 'Obra-prima de Aleijadinho e Mestre Ataíde.'],
    ['Igreja da Pampulha', 'igreja', 'Belo Horizonte', 'MG', -19.8580, -43.9780, 0.55, 'Igreja de abóbadas de concreto com painel de Portinari.'],
    ['Santuário do Bom Jesus de Matosinhos', 'igreja', 'Congonhas', 'MG', -20.5000, -43.8530, 0.55, 'Adro com os doze profetas esculpidos por Aleijadinho.'],
    ['Igreja e Convento de São Francisco (Salvador)', 'igreja', 'Salvador', 'BA', -12.9740, -38.5080, 0.6, 'Conhecida como Igreja de Ouro pelo interior em talha dourada.'],
    ['Igreja do Nosso Senhor do Bonfim', 'igreja', 'Salvador', 'BA', -12.9230, -38.5070, 0.65, 'Igreja das fitinhas e da Lavagem do Bonfim.'],
    ['Igreja do Rosário dos Pretos', 'igreja', 'Salvador', 'BA', -12.9718, -38.5085, 0.4, 'Igreja construída por irmandade negra no Pelourinho.'],
    ['Basílica de Nossa Senhora de Nazaré', 'igreja', 'Belém', 'PA', -1.4520, -48.4790, 0.55, 'Destino do Círio de Nazaré, uma das maiores procissões do mundo.'],
    ['Catedral Metropolitana de Fortaleza', 'igreja', 'Fortaleza', 'CE', -3.7230, -38.5260, 0.45, 'Catedral de estilo gótico e romano no centro de Fortaleza.'],
    ['Capela Dourada', 'igreja', 'Recife', 'PE', -8.0660, -34.8800, 0.4, 'Capela da Ordem Terceira de São Francisco, toda em talha dourada.'],
    ['Centro Cultural São Francisco', 'igreja', 'João Pessoa', 'PB', -7.1155, -34.8835, 0.45, 'Conjunto franciscano barroco com igreja, convento e museu de arte sacra.'],
    ['Catedral de Maringá', 'igreja', 'Maringá', 'PR', -23.4260, -51.9380, 0.45, 'Catedral cônica de 124 metros de altura.'],

    // ------------------------------------------------------------ cachoeiras
    ['Cataratas do Iguaçu', 'cachoeira', 'Foz do Iguaçu', 'PR', -25.6953, -54.4367, 0.95, 'Conjunto de cerca de 275 quedas, com a Garganta do Diabo.'],
    ['Cachoeira da Fumaça', 'cachoeira', 'Palmeiras', 'BA', -12.6000, -41.4600, 0.55, 'Queda de cerca de 340 m cuja água vira névoa antes de chegar ao chão.'],
    ['Cachoeira do Buracão', 'cachoeira', 'Ibicoara', 'BA', -13.3300, -41.2900, 0.4, 'Queda dentro de um cânion acessado a nado.'],
    ['Cachoeira de Paulo Afonso', 'cachoeira', 'Paulo Afonso', 'BA', -9.4000, -38.2100, 0.45, 'Cânion do São Francisco hoje regulado por usinas hidrelétricas.'],
    ['Cachoeira do Tabuleiro', 'cachoeira', 'Conceição do Mato Dentro', 'MG', -19.0500, -43.5200, 0.5, 'Maior cachoeira de Minas Gerais, com 273 m de queda.'],
    ['Cachoeira Véu de Noiva', 'cachoeira', 'Chapada dos Guimarães', 'MT', -15.4070, -55.8320, 0.5, 'Queda de 86 m em paredão de arenito.'],
    ['Cascata do Caracol', 'cachoeira', 'Canela', 'RS', -29.3110, -50.8560, 0.55, 'Queda de 131 m em meio a mata de araucárias.'],
    ['Salto do Itiquira', 'cachoeira', 'Formosa', 'GO', -15.3600, -47.4600, 0.4, 'Uma das maiores quedas livres do país.'],
    ['Cachoeira Santa Bárbara', 'cachoeira', 'Cavalcante', 'GO', -13.8600, -47.4500, 0.45, 'Poço de água azul-turquesa em território quilombola Kalunga.'],
    ['Cachoeira da Formiga', 'cachoeira', 'Mateiros', 'TO', -10.3400, -46.5500, 0.4, 'Pequena queda de água esverdeada no Jalapão.'],
    ['Salto do Yucumã', 'cachoeira', 'Derrubadas', 'RS', -27.1500, -53.8800, 0.4, 'Maior salto longitudinal do mundo, no Rio Uruguai.'],

    // ------------------------------------------------------------ teatros
    ['Teatro Amazonas', 'teatro', 'Manaus', 'AM', -3.1301, -60.0234, 0.85, 'Ópera do ciclo da borracha, com cúpula de telhas coloridas.'],
    ['Theatro Municipal do Rio de Janeiro', 'teatro', 'Rio de Janeiro', 'RJ', -22.9090, -43.1765, 0.7, 'Teatro eclético inspirado na Ópera de Paris.'],
    ['Theatro Municipal de São Paulo', 'teatro', 'São Paulo', 'SP', -23.5452, -46.6385, 0.7, 'Palco da Semana de Arte Moderna de 1922.'],
    ['Theatro da Paz', 'teatro', 'Belém', 'PA', -1.4533, -48.4930, 0.55, 'Teatro neoclássico do auge da borracha.'],
    ['Theatro José de Alencar', 'teatro', 'Fortaleza', 'CE', -3.7270, -38.5310, 0.5, 'Fachada art nouveau em estrutura metálica escocesa.'],
    ['Teatro de Santa Isabel', 'teatro', 'Recife', 'PE', -8.0620, -34.8780, 0.45, 'Teatro neoclássico de 1850 na Praça da República.'],
    ['Theatro Santa Roza', 'teatro', 'João Pessoa', 'PB', -7.1180, -34.8830, 0.4, 'Teatro de 1889, um dos mais antigos do país.'],
    ['Teatro Arthur Azevedo', 'teatro', 'São Luís', 'MA', -2.5300, -44.3010, 0.4, 'Um dos teatros mais antigos do Brasil, de 1817.'],
    ['Ópera de Arame', 'teatro', 'Curitiba', 'PR', -25.3850, -49.2760, 0.55, 'Teatro de estrutura tubular e cobertura transparente sobre uma pedreira.'],
    ['Theatro São Pedro', 'teatro', 'Porto Alegre', 'RS', -30.0330, -51.2300, 0.45, 'Teatro de 1858 na Praça da Matriz.'],
    ['Teatro Castro Alves', 'teatro', 'Salvador', 'BA', -12.9910, -38.5240, 0.45, 'Principal teatro da Bahia, com concha acústica.'],
    ['Teatro Nacional Cláudio Santoro', 'teatro', 'Brasília', 'DF', -15.7920, -47.8800, 0.45, 'Pirâmide de Niemeyer com fachada de blocos de Athos Bulcão.'],

    // ------------------------------------------------------------ fortes
    ['Forte de Copacabana', 'forte', 'Rio de Janeiro', 'RJ', -22.9864, -43.1874, 0.6, 'Forte de 1914 na ponta de Copacabana, hoje museu do Exército.'],
    ['Fortaleza de Santa Cruz da Barra', 'forte', 'Niterói', 'RJ', -22.9360, -43.1340, 0.45, 'Fortificação na entrada da Baía de Guanabara.'],
    ['Forte de Santo Antônio da Barra', 'forte', 'Salvador', 'BA', -13.0100, -38.5320, 0.65, 'Forte com o Farol da Barra, na entrada da Baía de Todos-os-Santos.'],
    ['Forte de São Marcelo', 'forte', 'Salvador', 'BA', -12.9730, -38.5170, 0.4, 'Único forte circular do Brasil, construído no mar.'],
    ['Fortaleza de Santa Catarina', 'forte', 'Cabedelo', 'PB', -6.9700, -34.8400, 0.45, 'Fortaleza do século XVI na foz do Rio Paraíba.'],
    ['Forte dos Reis Magos', 'forte', 'Natal', 'RN', -5.7570, -35.1950, 0.55, 'Forte em forma de estrela que deu origem à cidade de Natal.'],
    ['Forte do Presépio', 'forte', 'Belém', 'PA', -1.4560, -48.5050, 0.45, 'Marco de fundação de Belém, em 1616.'],
    ['Fortaleza de Nossa Senhora da Assunção', 'forte', 'Fortaleza', 'CE', -3.7230, -38.5240, 0.4, 'Fortificação que deu nome à capital cearense.'],
    ['Forte Orange', 'forte', 'Ilha de Itamaracá', 'PE', -7.8090, -34.8380, 0.4, 'Forte construído pelos holandeses em 1631.'],
    ['Forte das Cinco Pontas', 'forte', 'Recife', 'PE', -8.0710, -34.8810, 0.35, 'Forte holandês que abriga o Museu da Cidade do Recife.'],
    ['Fortaleza de Santa Cruz de Anhatomirim', 'forte', 'Governador Celso Ramos', 'SC', -27.4270, -48.5650, 0.4, 'Fortaleza do século XVIII numa ilha da baía norte de Florianópolis.'],
    ['Real Forte Príncipe da Beira', 'forte', 'Costa Marques', 'RO', -12.4260, -64.4230, 0.4, 'Maior fortificação portuguesa construída fora da Europa, às margens do Guaporé.'],
    ['Fortaleza de São José de Macapá', 'forte', 'Macapá', 'AP', 0.0300, -51.0500, 0.45, 'Fortaleza abaluartada do século XVIII na foz do Amazonas.'],

    // ------------------------------------------------------------ ilhas
    ['Fernando de Noronha', 'ilha', 'Fernando de Noronha', 'PE', -3.8540, -32.4240, 0.9, 'Arquipélago vulcânico, Patrimônio Natural da Humanidade.'],
    ['Ilha Grande', 'ilha', 'Angra dos Reis', 'RJ', -23.1500, -44.2300, 0.65, 'Ilha sem carros com trilhas e a Praia de Lopes Mendes.'],
    ['Ilhabela', 'ilha', 'Ilhabela', 'SP', -23.7780, -45.3580, 0.6, 'Arquipélago com dezenas de cachoeiras e naufrágios.'],
    ['Ilha do Mel', 'ilha', 'Paranaguá', 'PR', -25.5600, -48.3100, 0.5, 'Ilha preservada com farol e Gruta das Encantadas.'],
    ['Ilha de Superagui', 'ilha', 'Guaraqueçaba', 'PR', -25.4600, -48.2400, 0.3, 'Parque nacional habitado pelo mico-leão-de-cara-preta.'],
    ['Ilha do Cardoso', 'ilha', 'Cananéia', 'SP', -25.1200, -47.9800, 0.3, 'Ilha-parque estadual com comunidades caiçaras.'],
    ['Ilha Comprida', 'ilha', 'Ilha Comprida', 'SP', -24.7300, -47.5500, 0.3, 'Ilha-barreira de 74 km de praia contínua.'],
    ['Ilha de Boipeba', 'ilha', 'Cairu', 'BA', -13.6200, -38.9200, 0.4, 'Ilha tranquila vizinha a Morro de São Paulo.'],
    ['Ilha de Itaparica', 'ilha', 'Vera Cruz', 'BA', -12.9000, -38.6800, 0.5, 'Maior ilha da Baía de Todos-os-Santos.'],
    ['Arquipélago de Abrolhos', 'ilha', 'Caravelas', 'BA', -17.9600, -38.7000, 0.5, 'Primeiro parque nacional marinho do Brasil, berçário das baleias-jubarte.'],
    ['Ilha de Marajó', 'ilha', 'Soure', 'PA', -1.0000, -49.5000, 0.65, 'Maior ilha fluviomarítima do mundo, conhecida pelos búfalos.'],
    ['Ilha de Itamaracá', 'ilha', 'Ilha de Itamaracá', 'PE', -7.7500, -34.8300, 0.45, 'Ilha histórica com o Forte Orange e o Projeto Peixe-Boi.'],
    ['Ilha de Areia Vermelha', 'ilha', 'Cabedelo', 'PB', -7.0100, -34.8200, 0.4, 'Banco de areia que surge na maré baixa, cercado de piscinas naturais.'],
    ['Ilha do Bananal', 'ilha', 'Lagoa da Confusão', 'TO', -11.5000, -50.3000, 0.5, 'Maior ilha fluvial do mundo, entre os rios Araguaia e Javaés.'],
  ];

  raiz.LOCAIS_SEMENTE = L.map(([nome, categoria, cidade, uf, lat, lon, relevancia, descricao]) => ({
    nome, categoria, cidade, uf, lat, lon, relevancia, descricao, imagem: null, fonte: null,
  }));
})(typeof self !== 'undefined' ? self : this);
